### ISSUE TITLE
Error in your code

### ISSUE THREAD

**Issue by Fazil-vk** [phaticusthiccy/Open-APIs#15]
/root/whatsapp-bot/node_modules/@phaticusthiccy/open-apis/TextMaker/lib/textmaker/glowtxt.js:198
const axios = require("axios");
SyntaxError: Identifier 'axios' has already been declared

when tour pakage installing, still getting this errored package

**Comment by Fazil-vk** [comment]
> /root/whatsapp-bot/node_modules/@phaticusthiccy/open-apis/TextMaker/lib/textmaker/glowtxt.js:198 const axios = require("axios"); SyntaxError: Identifier 'axios' has already been declared
> 
> when tour pakage installing, still getting this errored package

How to fix this?

**Comment by Fazil-vk** [comment]
> > /root/whatsapp-bot/node_modules/@phaticusthiccy/open-apis/TextMaker/lib/textmaker/glowtxt.js:198 const axios = require("axios"); SyntaxError: Identifier 'axios' has already been declared
> > when tour pakage installing, still getting this errored package
> 
> How to fix this?

"@phaticusthiccy/open-apis": "github:phaticusthiccy/Open-APIs"
fixed by using this

**Comment by phaticusthiccy** [comment]
Yeah, I Know. I just finished Instagram Scraper. I was waiting for the update to be finished. I will update during the day.

**Comment by phaticusthiccy** [comment]
Fixed All. 
Latest Tag: https://github.com/phaticusthiccy/Open-APIs/releases/tag/1.2.1
Latest Vers: [1.2.1](https://www.npmjs.com/package/@phaticusthiccy/open-apis)

**Comment by phaticusthiccy** [comment]
Also ı dont recommend to use direct repository. Stable versions avaliable on npm registery.

**Comment by Fazil-vk** [comment]
> Also ı dont recommend to use direct repository. Stable versions avaliable on npm registery.

Ok, thank you
