### ISSUE TITLE
User not found when i trying insta stories

### ISSUE THREAD

**Issue by officialdittaz** [phaticusthiccy/Open-APIs#17]
Error: User Not Found!
    at Object.insta_story (/storage/emulated/0/SelfBot/node_modules/@phaticusthiccy/open-apis/InstaDownloader/start/instagram_story.js:12:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Thisy My script

case 'ig':

setReply(mess.wait)
if (!q) return setReply('Linknya?')
igreel = q.includes("https://www.instagram.com/reel/")
igstories = q.includes("https://instagram.com/stories/")

if(igreel){
Download.insta_reel(q).then(async (data) => {
sendFileFromUrl(`${data.url}`, video, {quoted: dev, caption: `Nih`})
console.log(data)
console.log(data.url)
})
} else if(igstories){
Download.insta_story(q).then(async (data) => {
	console.log(data.stories)
 //sendFileFromUrl(`${data.stories.url}`, video, {quoted: dev, caption: `Nih`})
})
} else {
var { igDownloader } = require('./lib/igdown')
   res = await igDownloader(`${q}`).catch(e => {
return setReply(mess.error.api)
})
console.log(res)
sendFileFromUrl(`${res.result.link}`, video, {quoted: dev, caption: `${res.result.desc}`})
}
break
![Screenshot_2022-02-01-11-55-13-181_com termux](https://user-images.githubusercontent.com/86673643/151914774-aff6ae0e-40e9-4bee-acb3-39a71dacf7c6.jpg)

**Comment by phaticusthiccy** [comment]
Looks like token mismatch. Lemme try something.

**Comment by phaticusthiccy** [comment]
Yeah, ı was right. I used "used-tokens" for csrf bypass but thats not the point. The point is when headers setted once for csrf with the open cookies, they works soo unstable. But its easy to fix it. If ı complate the new version in a day, ı will publish new version for Open-APIs with the new module.

**Comment by phaticusthiccy** [comment]
When the new version published, ı will close the issue. Check the usage again when its done. This time maybe ı will change the repsonses.

**Comment by phaticusthiccy** [comment]
Fixed and Renewed.

Commit: https://github.com/phaticusthiccy/Open-APIs/commit/4de6c57a23386d59ea3ba154367d0209478fc234
New Response: https://github.com/phaticusthiccy/Open-APIs/tree/main/InstaDownloader#story-downloader
PR: https://github.com/phaticusthiccy/Open-APIs/pull/18

**Comment by phaticusthiccy** [comment]
The video meta may wont work with the `sendFileFromUrl()`
If it throws error, you can use simply this code.

```js
const request = require("request")
const fs = require("fs")
var url = "video url"
var path = "./story.mp4"

request(url).pipe(fs.createWriteStream(path))
```

`.pipe()` and `createWriteStream()` can return data URI document to media files.
