### ISSUE TITLE
[BUG] stuck when i trying install on termux

### ISSUE THREAD

**Issue by officialdittaz** [phaticusthiccy/Open-APIs#24]
I dont know why, when i trying install on termux and its stuck, you try![Screenshot_2022-02-18-16-47-39-717_com.miui.gallery.jpg](https://user-images.githubusercontent.com/86673643/154659303-914657b5-842b-4fb0-97e2-c848630de36f.jpg)

**Comment by phaticusthiccy** [comment]
Please, set dependent on `package.json`
Then go by with `npm install`

**Comment by phaticusthiccy** [comment]
Also you can use `npm view @phaticusthiccy/open-apis version` 
Then you can check the latest version [here](https://img.shields.io/npm/v/@phaticusthiccy/open-apis?color=6E3BC6&label=Open-APIs&logoColor=6E3BC6)

**Comment by officialdittaz** [comment]
Ok terimakasih 🤗

**Comment by phaticusthiccy** [comment]
Is it solved?

**Comment by phaticusthiccy** [comment]
Please, ping me if it solved. Or else, ı will close this report.

**Comment by phaticusthiccy** [comment]
Closed for inactivity.
